services:
  orchestrator:
    image: ghcr.io/localai/orchestrator:latest
    container_name: ai-reading-orchestrator
    env_file:
      - ../ops/.env.example
    environment:
      - SETTINGS_PATH=/app/config/settings.yml
    volumes:
      - ../agents/configs:/app/config:ro
      - ../agents/prompts:/app/prompts:ro
      - ../data/vectors:/app/vectors
      - ../logs:/app/logs
    ports:
      - "8080:8080"
    depends_on:
      - chroma

  chroma:
    image: chromadb/chroma:latest
    container_name: ai-reading-chroma
    volumes:
      - ../data/vectors:/chroma/index
    environment:
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_HTTP_PORT=8000
    ports:
      - "8000:8000"

  qdrant:
    image: qdrant/qdrant:latest
    container_name: ai-reading-qdrant
    volumes:
      - qdrant_storage:/qdrant/storage
    ports:
      - "6333:6333"
    environment:
      - QDRANT__SERVICE__GRPC_PORT=6334
    deploy:
      replicas: 0

  ingest:
    image: python:3.11-slim
    working_dir: /app
    volumes:
      - ..:/app
    command: ["python", "scripts/ingest.py"]

  analytics:
    image: python:3.11-slim
    working_dir: /app
    volumes:
      - ..:/app
    command: ["python", "scripts/adoption_report.py"]

  agents:
    image: python:3.11-slim
    working_dir: /app
    volumes:
      - ..:/app
    command: ["python", "scripts/agent_runner.py"]

volumes:
  qdrant_storage:
